version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - ./docker-mongo/cache:/data/db
    ports:
      - "27017:27017"
    tty: true
    
  # next:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - MONGO_URI=mongodb://mongodb:27017
  #   depends_on:
  #     - mongodb

