version: "3.9"
services:
  mongodb1:
    image: mongo
    container_name: mongodb1-dev
    command: mongod --replSet rs0
    volumes:
      - ./docker-mongo/cache:/data/db
    ports:
      - "27017:27017"
    tty: true
    networks:
      - mongo-cluster

  mongodb2:
    image: mongo
    container_name: mongodb2-dev
    command: mongod --replSet rs0
    ports:
      - "27018:27017"
    tty: true
    networks:
      - mongo-cluster

  mongodb3:
    image: mongo
    container_name: mongodb3-dev
    command: mongod --replSet rs0
    ports:
      - "27019:27017"
    tty: true
    networks:
      - mongo-cluster

  mongo-init-replica:
    image: mongo
    container_name: mongo-init-replica-dev
    command: >
      mongosh --host mongodb1:27017
        --eval "rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'mongodb1:27017'}, {_id: 1, host: 'mongodb2:27017'}, {_id: 2, host: 'mongodb3:27017'}]})"
    depends_on:
      - mongodb1
      - mongodb2
      - mongodb3
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
