name: Node.js CI

on:
  push:
    branches: [to-cloud-aws]
  pull_request:
    branches: [to-cloud-aws]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production

    strategy:
      matrix:
        node-version: [18.14.2]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - run: npm test
